[profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth_rpc_url = "https://rpc.tenderly.co/fork/5cb5b14e-31e8-4f64-808e-e5d75e13c117"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
